language: minimal

dist: focal

services:
  - docker

branches:
  only:
  - main

script:
  - docker --version
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}"
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --noavx

after_success:
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com