language: minimal

dist: focal

services:
  - docker

# branches:
#   only:
#   - main
#   - develop

script:
  - docker pull "mindsync/python:0.1.${TRAVIS_BUILD_NUMBER}-gpu-p37-cu11" || true
  - docker pull "mindsync/python:0.1.${TRAVIS_BUILD_NUMBER}-gpu-p37-cu11-noavx" || true
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}"
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --noavx

after_success:
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com