language: minimal

dist: focal

services:
  - docker

cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true

before_cache:
- docker save -o docker_images/images.tar $(docker images -aq)

jobs:
  include:
    - stage: build only
      if: branch != main
      script:
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx

    - stage: build & push
      if: branch = main
      script:
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
        - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx

      after_success:
        - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
        - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com

