language: minimal

dist: focal

services:
  - docker

# cache:
#   directories:
#   - "${HOME}/.build"

# stages:
# - name: build
# - name: push
#   if: branch = main

# jobs:
#   include:
#     - stage: build
#       script:
#         - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
#         - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx

#     - stage: push
#       after_success:
#         - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
#         - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -

script:
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache
  - ./build --build-num "${TRAVIS_BUILD_NUMBER}" --use-cache --noavx

after_success:
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" -
  - echo "${DOCKER_PASSWORD}" | ./push --build-num "${TRAVIS_BUILD_NUMBER}" --noavx -

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com