language: minimal

dist: bionic

services:
  - docker

branches:
  only:
  - main

script:
  - addgroup --gid 100 users
  - useradd -m -s /bin/bash -N --uid 1000 mindsync 
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx

after_success:
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx
