language: minimal

dist: focal

services:
  - docker

branches:
  only:
  - main

script:
  - docker --version
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx

after_success:
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx

notifications:
  email:
    - asfedorov@gmail.com
    - k@mindsync.ai
    - yellow4x@gmail.com