language: minimal

dist: bionic

services:
  - docker

branches:
  only:
  - main

script:
  - docker --version
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./build --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx

after_success:
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}"
  - ./push --tag-suffix "${TRAVIS_BUILD_NUMBER}" --noavx
